before_commands:
    - "composer install --dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["app/models/*", "tests/*"]
    php_cpd:
        enabled: true
        filter:
            paths: ["app/models/*", "tests/*"]
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            paths: ["app/models/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["vendor", "public", "bootstrap"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["app/models/*", "tests/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["app/models/*", "tests/*"]
    php_analyzer:
        enabled: false
        filter:
            paths: ["app/models/*"]
    sensiolabs_security_checker: true